// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PaymentLibrary$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PaymentLibrary";
  readonly sourceName: "contracts/libraries/PaymentLibrary.sol";
  readonly abi: [{"inputs":[],"name":"InvalidAmount","type":"error"},{"inputs":[],"name":"InvalidFee","type":"error"},{"inputs":[],"name":"InvalidTimeframe","type":"error"},{"inputs":[],"name":"PaymentTooLarge","type":"error"},{"inputs":[],"name":"PaymentTooSmall","type":"error"},{"inputs":[],"name":"BASIS_POINTS","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"MAX_FEE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"MAX_PAYMENT","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"MIN_PAYMENT","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x60c2610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060515760003560e01c8063b1c1008c146056578063bc063e1a146073578063e1f1c4a714607b578063eb566e91146083575b600080fd5b606164e8d4a5100081565b60405190815260200160405180910390f35b60616101f481565b606161271081565b6061620f42408156fea26469706673582212205e6fccffabfc6961d28d99d9312cea0341d5158b268fbd713dc65aa1231ed96a64736f6c63430008130033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040526004361060515760003560e01c8063b1c1008c146056578063bc063e1a146073578063e1f1c4a714607b578063eb566e91146083575b600080fd5b606164e8d4a5100081565b60405190815260200160405180910390f35b60616101f481565b606161271081565b6061620f42408156fea26469706673582212205e6fccffabfc6961d28d99d9312cea0341d5158b268fbd713dc65aa1231ed96a64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/PaymentLibrary.sol";
  readonly buildInfoId: "solc-0_8_19-8d5505436d98f456ce051f3853259a786d1b64f2";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PaymentLibrary"]: PaymentLibrary$Type;
    ["contracts/libraries/PaymentLibrary.sol:PaymentLibrary"]: PaymentLibrary$Type;
  }
}